### ISSUE TITLE
Remove Facebook Page Plugin

### ISSUE THREAD

**Issue by hochleitner** [Playful-Interactive-Environments/pie.fh-hagenberg.at#12]
Remove the Facebook Page Plugin on the Home page and replace it with icons that link to the respective social media sites.

**Comment by hochleitner** [comment]
Consider using FontAwesome for icons: https://fortawesome.github.io/Font-Awesome/

**Comment by tomheller** [comment]
If it is just 2 - 3 social icons, consider inlined svgs instead of loading a whole additional fontset for it.

**Comment by hochleitner** [comment]
I understand the concern, yet I'm struggling to find appropriate SVGs. Flaticon is somewhat limited plus some icons (e.g., Google+) are outdated, some of the SVGs seem to be created with Illustrator which creates crappy and bloated SVG markup. Projects like https://github.com/adamfairhead/webicons might be too much either (plus it's not really maintained and a few icons are outdated as well), additionally if possible, I'd like to avoid CC-Attrib licenses (although that's not really an issue). 

Using a font on the other hand would make styling the icons easy (changing color on hover, transitions, etc.), I'm not sure (experienced/creative enough) how to achieve this with SVG.
Suggestions welcome. ^^

**Comment by tomheller** [comment]
All understandable concerns. I'm not on my development machine but I will try and whip something together. 

The target is to take fontawesome and convert it to an svg font, use only google and facebook paths from them. 
Then inline the svgs to the html with stripped fill attributes, which makes it easily styleable in css.
