### ISSUE TITLE
Split up projects into categories

### ISSUE THREAD

**Issue by hochleitner** [Playful-Interactive-Environments/pie.fh-hagenberg.at#25]
Since the number of projects is growing, they should probably be split up in multiple categories, each with their own heading. Research and student projects could be a first step to categorize.

**Comment by tomheller** [comment]
@hochleitner Will you need some help with that?

**Comment by hochleitner** [comment]
I think I should be fine, thanks. If the need arises I'll come back at you, thanks for the help!
