### ISSUE TITLE
Invisible Walls Projekt Doku Website

### ISSUE THREAD

**Issue by michaellankes** [Playful-Interactive-Environments/pie.fh-hagenberg.at#28]

**Comment by michaellankes** [comment]
Lieber Wolfi,

Wir senden die die Files zur Dokumentation von Invisible Walls - bitte auf die Website stellen.

Grüße,

Michi & Jürgen

[InvisibleWallsDesciption_Juergen.docx](https://github.com/Playful-Interactive-Environments/pie.fh-hagenberg.at/files/609099/InvisibleWallsDesciption_Juergen.docx)
![invisiblewalls_01](https://cloud.githubusercontent.com/assets/17197361/20565807/3d616786-b193-11e6-8713-e4da4d82d7af.jpg)
![invisiblewalls_02](https://cloud.githubusercontent.com/assets/17197361/20565806/3d5e2ab2-b193-11e6-90fa-6320bdc1418c.jpg)
![invisiblewalls_03](https://cloud.githubusercontent.com/assets/17197361/20565810/3d6966c0-b193-11e6-9cbe-b0e4fc02cf64.jpg)
![invisiblewalls_04](https://cloud.githubusercontent.com/assets/17197361/20565811/3d6aeb4e-b193-11e6-85d2-5c7a28e7c176.jpg)
![invisiblewalls_05](https://cloud.githubusercontent.com/assets/17197361/20565809/3d63ed62-b193-11e6-9b61-fe6a5d383d46.jpg)
![invisiblewalls_06](https://cloud.githubusercontent.com/assets/17197361/20565808/3d622720-b193-11e6-931b-8f6eefef0404.jpg)
![invisiblewalls_07](https://cloud.githubusercontent.com/assets/17197361/20565812/3d77e178-b193-11e6-8554-756146f104c5.jpg)

Video findest du unter: ...\FileBox\Playful Interactive Environments\Projects\Not Funded\ViennaDesignWeek\Videos

**Comment by hochleitner** [comment]
Wird eingebaut, danke!
